<?php
/**
 * Yireo EmailTester for Magento 
 *
 * @package     Yireo_EmailTester
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Source License
 */

$warnings = $this->getWarnings();
?>
<?php if(!empty($warnings)) : ?>
<ul class="messages">
    <li class="error-msg">
        <ul>
        <?php foreach($warnings as $warning): ?>
            <li><?php echo $warning; ?></li>
        <?php endforeach; ?>
        </ul>
    </li>
</ul>
<?php endif; ?>
