<?php
/**
 * Yireo EmailTester for Magento 
 *
 * @package     Yireo_EmailTester
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Source License
 */

$customer = $this->getCustomer();
?>
<div class="fieldset">
<table cellspacing="0" class="form-list" style="width:100%">
    <tbody>
        <tr class="headings">
            <td width="100" class="label">
                <label for="customer_id"><?php echo Mage::helper('emailtester')->__('Customer')?></label>
            </td>
            <td width="80" class="value">
                <input name="customer_id" id="customer_id" class="input-text" style="width:50px;" 
                    value="<?php echo $this->getCustomerId(); ?>" placeholder="ID" />
            </td>
            <td class="value">
                <input name="customer_search" id="customer_search" class="input-text" style="width:300px;"
                    value="<?php echo $this->getCustomerSearch(); ?>" placeholder="<?php echo Mage::helper('emailtester')->__('Customer search')?>" />
            </td>
        </tr>
    </tbody>
</table>
</div>
