<?php
/**
 * Yireo EmailTester for Magento 
 *
 * @package     Yireo_EmailTester
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Source License
 */

$customer = $this->getCustomer();
?>
<div class="fieldset">
<table cellspacing="0" class="form-list" style="width:100%">
    <tbody>
        <tr class="headings">
            <td width="100" class="label">
                <label for="customer_id"><?php echo Mage::helper('emailtester')->__('Customer')?></label>
            </td>
            <td width="80" class="value">
                <?php $help = Mage::helper('emailtester')->__('Type in the numerical ID of the customer, or use the search on the right.'); ?>
                <input name="customer_id" id="customer_id" class="input-text" style="width:50px;" 
                    value="<?php echo $this->getCustomerId(); ?>" placeholder="<?php echo $this->__('ID'); ?>" title="<?php echo $help; ?>" />
            </td>
            <td class="value">
                <?php $placeholder = Mage::helper('emailtester')->__('Start typing to search for a customer'); ?>
                <?php $help = Mage::helper('emailtester')->__('Start typing to search for a customer. A dropdown will show you results automatically.'); ?>
                <input name="customer_search" id="customer_search" class="input-text" style="width:300px;"
                    value="<?php echo $this->getCustomerSearch(); ?>" placeholder="<?php echo $placeholder; ?>" title="<?php echo $help; ?>" />

                <?php if($this->getCustomerOptions()) : ?>
                <select name="customer_select" id="customer_select">
                    <?php foreach($this->getCustomerOptions() as $option) : ?>
                    <?php $selected = ($option['current']) ? 'selected="selected"' : null; ?>
                    <option value="<?php echo $option['value']; ?>" <?php echo $selected; ?>><?php echo $option['label']; ?></option>
                    <?php endforeach; ?>
                </select>
                <?php endif; ?>

                <button type="button" class="cancel" onclick="clearInput('customer_id', 'customer_search', 'customer_select');">
                    <span><span><span><?php echo $this->__('Clear'); ?></span></span></span>
                </button>
            </td>
        </tr>
    </tbody>
</table>
</div>
