<?php
/**
 * Yireo EmailTester for Magento 
 *
 * @package     Yireo_EmailTester
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Source License
 */

?>
<div class="fieldset">
<table cellspacing="0" class="form-list">
    <tbody>
        <tr class="headings">
            <td width="100" class="label">
                <label for="order_id"><?php echo Mage::helper('emailtester')->__('Order')?></label>
            </td>
            <td width="80" class="value">
                <input name="order_id" id="order_id" class="input-text required-entry" style="width:50px;" 
                    value="<?php echo $this->getOrderId(); ?>" placeholder="ID" />
            </td>
            <td class="value">
                <input name="order_search" id="order_search" class="input-text" style="width:300px"
                    value="<?php echo $this->getOrderSearch(); ?>" placeholder="<?php echo Mage::helper('emailtester')->__('Order search')?>" />
            </td>
        </tr>
    </tbody>
</table>
</div>
