<?php
/**
 * Yireo EmailTester for Magento 
 *
 * @package     Yireo_EmailTester
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Source License
 */
?>
<div class="fieldset">
<table cellspacing="0" class="form-list" style="width:100%">
    <tbody>
        <tr class="headings">
            <td width="100" class="label">
                <label for="product_id"><?php echo Mage::helper('emailtester')->__('Product')?></label>
            </td>
            <td width="80" class="value">
                <?php $help = Mage::helper('emailtester')->__('Type in the numerical ID of the product, or use the search on the right.'); ?>
                <input name="product_id" id="product_id" class="input-text" style="width:50px;" 
                    value="<?php echo $this->getProductId(); ?>" placeholder="<?php echo $this->__('ID'); ?>" title="<?php echo $help; ?>" />
            </td>
            <td class="value">
                <?php $placeholder = Mage::helper('emailtester')->__('Start typing to search for a product'); ?>
                <?php $help = Mage::helper('emailtester')->__('Start typing to search for a product. A dropdown will show you results automatically.'); ?>
                <input name="product_search" id="product_search" class="input-text" style="width:300px;"
                    value="<?php echo $this->getProductSearch(); ?>" placeholder="<?php echo $placeholder; ?>" title="<?php echo $help; ?>" />

                <?php if($this->getProductOptions()) : ?>
                <select name="product_select" id="product_select">
                    <?php foreach($this->getProductOptions() as $option) : ?>
                    <?php $selected = ($option['current']) ? 'selected="selected"' : null; ?>
                    <option value="<?php echo $option['value']; ?>" <?php echo $selected; ?>><?php echo $option['label']; ?></option>
                    <?php endforeach; ?>
                </select>
                <?php endif; ?>

                <button type="button" class="cancel" onclick="clearInput('product_id', 'product_search');">
                    <span><span><span><?php echo $this->__('Clear'); ?></span></span></span>
                </button>
            </td>
        </tr>
    </tbody>
</table>
</div>
