<?php
/**
 * EmailTester extension for Magento
 *
 * @package     Yireo_EmailTester
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright (c) 2018 Yireo.com
 * @license     Open Software License
 */

/**
 * @var $this Yireo_EmailTester_Block_Head_Script
 */
?>
<script>
    var emailtester_customer_ajax_url = '<?php echo $this->getAjaxCustomerUrl() ?>';
    var emailtester_product_ajax_url = '<?php echo $this->getAjaxProductUrl(); ?>';
    var emailtester_order_ajax_url = '<?php echo $this->getAjaxOrderUrl(); ?>';
    var emailtester_send_url = '<?php echo $this->getSendUrl(); ?>';
    var emailtester_output_url = '<?php echo $this->getOutputUrl(); ?>';
    var emailtester_default_store_id = <?php echo (int)$this->getDefaultStoreId(); ?>;
</script>
