<?php
/**
 * EmailTester extension for Magento
 *
 * @package     Yireo_EmailTester
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2018 Yireo.com
 * @license     Open Software License
 */

/**
 * @var $this Yireo_EmailTester_Block_Form
 */
?>

<div class="emailtester-container">
    <div class="content-header">
        <table cellspacing="0">
            <tr>
                <td class="left-col"><h3 class="icon-head head-tag"><?php echo $this->__('Email Tester'); ?></h3></td>
                <td class="formbuttons">
                    <?php echo $this->getChildHtml('send_button'); ?>
                    <?php echo $this->getChildHtml('output_button'); ?>
                </td>
            </tr>
        </table>
    </div>

    <?php echo $this->getChildHtml('store_switcher'); ?>

    <div id="alert_messages_block"><?php echo $this->getMessageHtml() ?></div>

    <div class="entry-edit">
        <form action="<?php echo $this->getSendUrl() ?>" method="post" id="emailtester_form">
            <?php echo $this->getChildHtml('accordion') ?>
            <?php echo $this->getBlockHtml('formkey') ?>
            <input type="hidden" name="store" value="<?php echo $this->getStore(); ?>"/>
        </form>
    </div>

    <?php echo $this->getChildHtml('check') ?>

    <div class="version">
        <div class="inner">
            EmailTester <?php echo $this->getVersion(); ?> &nbsp; - &nbsp;
            <?php echo $this->__('Copyright'); ?> &copy; 2014 <a href="http://www.yireo.com/" target="_new">Yireo</a>
            <img src="<?php echo $this->getSkinUrl('images/emailtester/yireo.png'); ?>"
                 style="display:inline;padding-left:5px"/>
        </div>
    </div>
</div>

<script type="text/javascript">
    jQuery(function () {
        var tooltips = jQuery('[title]').tooltip({
            position: {
                my: "left top",
                at: "right+5 top-5"
            }
        });
    });

    var emailtesterForm = new varienForm('emailtester_form');
</script>

<?php
echo ini_get('memory_limit');
?>
