<?php
/**
 * EmailTester extension for Magento
 *
 * @package     Yireo_EmailTester
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo.com
 * @license     Open Software License
 */

/**
 * @var $this Yireo_EmailTester_Block_Print
 */
@header('Content-type: text/html; charset=utf-8');
?>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
</head>
<?php echo trim($this->getBody()); ?>
</html>
